Update fork (#3)
* [fix] to NO USE DMA-BUF EXPORT if CONFIG_DMA_SHARED_BUFFER is not set. (see issues #122 and #123)
[update] DRIVER_VERSION to 4.8.2-RC1

* [update] DRIVER_VERSION to 4.8.2

* [update] Readme.md

* [add] the kernel configuration options to Kconfig.
      * U_DMA_BUF_DEBUG
      * U_DMA_BUF_QUIRK_MMAP
      * U_DMA_BUF_IN_KERNEL_FUNCTIONS
      * U_DMA_BUF_IOCTL
      * U_DMA_BUF_EXPORT
[add] the following command line variables to Makefile for build with the out of kernel tree.
      * CONFIG_U_DMA_BUF_DEBUG
      * CONFIG_U_DMA_BUF_QUIRK_MMAP
      * CONFIG_U_DMA_BUF_IN_KERNEL_FUNCTIONS
      * CONFIG_U_DMA_BUF_IOCTL
      * CONFIG_U_DMA_BUF_EXPORT
[change] the following reconfigurable options in u-dma-buf.c so that they chan be changed externally.
      * UDMABUF_DEBUG
      * USE_QUIRK_MMAP
      * IN_KERNEL_FUNCTIONS
      * IOCTL_VERSION
      * USE_DMA_BUF_EXPORT
[update] DRIVER_VERSION to 4.9.0-RC1

* [update] Readme.md

* [change] so that if the constant is defined with -DU_DMA_BUF_XXXX at build, it takes precedence over CONFIG_U_DMA_BUF_XXXX in Kconfig.
[fix] "warning: ‘udmabuf_get_option_property’ defined but not used [-Wunused-function]" when U_DMA_BUF_QUIRK_MMAP!=1
[update] DRIVER_VERSION to 4.9.0-RC2

* [fix] issue in which the configuration report output when info_enable&0x4!=0 was not constant value.
[update] DRIVER_VERSION to 4.9.0-RC3

* [update] DRIVER_VERSION to 4.9.0

* [add] U_DMA_BUF_CONFIG kernel configuration option to Kconfig.
[change] Kconfig so that the followng kernel configuration options can be changed when U_DMA_BUF_CONFIG=y.
      * U_DMA_BUF_DEBUG
      * U_DMA_BUF_QUIRK_MMAP
      * U_DMA_BUF_IN_KERNEL_FUNCTIONS
      * U_DMA_BUF_IOCTL
      * U_DMA_BUF_EXPORT
[add] U_DMA_BUF_CONFIG option to Makefile.
[change] u-dma-buf.c to set the following kernel configuration option when U_DMA_BUF_CONFIG=0.
      * UDMABUF_DEBUG=1
      * USE_QUIRK_MMAP=1
      * IN_KERNEL_FUNCTIONS=1
      * IOCTL_VERSION=2
      * USE_DMA_BUF_EXPORT=1
[update] DRIVER_VERSION to 5.0.0-RC1

* [update] DRIVER_VERSION to 5.0.0

* [update] Readme.md

* [fix] "error: redefinition of ‘dma_map_sgtable’" and "error: redefinition of ‘dma_unmap_sgtable’" when building with linux kernel v5.4.233 or higher but less than v5.5.0.
[update] DRIVER_VERSION to 5.0.1

* [update] Readme.md

* [fix] to use strscpy() instead of strlcpy(), because strlcpy() is obsolete in linux kernel 6.8 and later.
[update] DRIVER_VERSION to 5.0.2

* [update] Readme.md

* [update] Makefile for build on riscv and other machines
[update] DRIVER_VERSION to 5.0.3

* [update] Readme.md

* Fix platform_driver.remove for kernel > 6.11

* [rename] udmabuf_platform_driver_remove_status() -> _udmabuf_platform_driver_remove()

* [add] prototype declarations for in-kernel functions

* [update] DRIVER_VERSION to 5.1.0

* [update] Readme.md

* Fix MODULE_IMPORT_NS compile error for kernel >= 6.13

The module macro 'MODULE_IMPORT_NS' has converted symbol namespace to
string literal without '__stringify' by [1] since 6.13:

-#define MODULE_IMPORT_NS(ns)	MODULE_INFO(import_ns, __stringify(ns))
+#define MODULE_IMPORT_NS(ns)	MODULE_INFO(import_ns, ns)

[1] https://git.kernel.org/torvalds/c/cdd30ebb1b9f

Signed-off-by: Haiyue Wang <haiyuewa@163.com>

* [fix] MODULE_IMPORT_NS compile error for kernel >= 6.13

* [update] DRIVER_VERSION to 5.2.0

* [update] Readme.md

* support bind per dev

* [update] DRIVER_VERSION to 5.3.0-RC1

* [rename] module parameter udmabuf_bind[0-7] -> udmabuf[0-7]_bind
[update] DRIVER_VERSION to 5.3.0-RC2

* [add]    udmabuf_static_device_list[] to bind a parent device for each udmabuf_static_device
[delete] udmabuf_static_parent_device instead
[update] DRIVER_VERSION to 5.3.0-RC3

* [add]    udmabuf_static_device_destroy_all() to put_device() the bound parent device of udmabuf_static_device when removing kernel module.
[update] DRIVER_VERSION to 5.3.0-RC4

* [add] parent field to struct udmabuf_device_entry to put_device(parent) when removing an entry.
[delete] udmabuf_static_device_list[] which is no longer needed for the above reasons.
[delete] udmabuf_static_device_delete() which is no longer needed for the above reasons.
[delete] udmabuf_static_device_delete_all() which is no longer needed for the above reasons.
[update] DRIVER_VERSION to 5.3.0-RC4

* [update] DRIVER_VERSION to 5.3.0

* [update] Readme.md

* [update] Readme.md

* add gitignore

* [update] .gitignore to refine ignore rules for kerenel module development.

---------

Signed-off-by: Haiyue Wang <haiyuewa@163.com>
Co-authored-by: Ichiro Kawazome <ichiro_k@ca2.so-net.ne.jp>
Co-authored-by: Kevin Tom <kevin@servaenergy.com>
Co-authored-by: Haiyue Wang <haiyuewa@163.com>
Co-authored-by: Steve Hu <Steve.Hu@innogritcorp.com>
Co-authored-by: Ebihara Yusuke <yusuke@ebihara.me>
Co-authored-by: Dushmanta Mohaptra <dmohapatra@ws01.tsavoritesi.net>